### ISSUE TITLE
FMIFlux ScaleSum is not able to handle more than one scaled sum

### ISSUE THREAD

**Issue by juguma** [ThummeTo/FMIFlux.jl#100]
The ScaleSum layer is a helpful way to add, e.g. NN-output with FMU-output, however it only works for a Vector of the same length as the scale which has been used in the definition of the ScaleSum layer (in the provided examples, it is 2).

ScaleSum should be able to handle this for more than a Vector. My proposal would be to prepare it for an n-Vector of m-Vectors (where m is the length of the scale vector when defining the layer, typically m=2) and n is the number of inputs that are to be "scale-summed".

Here's a minimal example (including a proposed solution):
```
using FMIFlux
scale = [0.7 ,0.3]
gates = ScaleSum(scale)

#input as n-Vector of 2-vectors
b1=[1.0,2.0] #<-this is the variant for which ScaleSum works already
b3=[[1.0,2.0],[1.0,2.0],[1.0,2.0]] #<-this is for what it should work
b1Vec=[[1.0,2.0]] #<-this Vector of Vector variant for 1 value pair

#proposed Variant for the ScaleSum-function:
function scsum(x)
    if length(x[1])==1#<-input is not Vector of Vector,but only Vector (with the lenght equal to scale)
        x_proc = [sum(x.*scale)]
    else
        x_proc = similar(x[1],length(x))
        for i in eachindex(x)
            x_proc[i] = sum(x[i].* scale)
        end
    end
    return x_proc
end

#test
using BenchmarkTools
@btime scsum(b1)
#vs.
@btime gates(b1)
#<-same time, same resources, same result
@btime scsum(b1Vec)
#<-same resources, same result as b1, even though it goes through the else branch
@btime scsum(b3)
```

**Comment by juguma** [comment]
I just realized you already tackled that in v0.10.2 with the new "groups" parameter in ScaleSum. Now what I proposed here is obsolete or should only be considered if it turns out it is more performant (together with the PairWithCacheRetrieve #101).

**Comment by ThummeTo** [comment]
Dear @juguma,
thanks! Can we wait another week or so, because there will be MAJOR changes to FMIFlux.jl (only good ones of course) and many improvements. However I think the proposed layer will work in the next release too without changes.

**Comment by juguma** [comment]
Dear @ThummeTo, sure we can wait (since the modifications are rather feature than bug). And MAJOR (good) changes are a good reason to wait.

**Comment by ThummeTo** [comment]
Little teaser: Differentiable event indicators ;-)

**Comment by juguma** [comment]
Dear @ThummeTo, the findings of today's discussion and yet another try-and-error-session on my side:
- what I propose looks nice (that's me saying it and you have to admit ;-)), but has some issues.
  Most relevant is that the currently defined layers cannot be differentiated with Zygote.
To work around this, we decided to use `collect` in the layer definitions, i.e.
`x_proc = collect(sum(x[i].* l.scale[i]) for i in eachindex(x))`
in the ScaleSum
and 
`collect([l.cacheLayer.cache[tid][idx[i]], x[i]] for i in 1:lastindex(idx))`
in the `PairWithCacheRetrieve`-Layer.
This modification helps in the ScaleSum layer, now Zygote.gradient is happy, but it doesn't in the CacheRetrieve-Layer. I don't know why.
- Julia is faster with its multiple dispatch than with if-then-else-conditions. I tried to split the ScaleSumN into two functions - for vectors, and for vectors of vectors, however I failed to define the types properly. 
Closest to successful was:
`function (l::ScaleSumN)(x::AbstractVector{<:Union{Float32,Float64}})`
and
`function (l::ScaleSumN)(x::Union{AbstractVector{Vector{Float64}},AbstractVector{Vector{Float32}}})`,
but it returned the wrong output for `gatesAN1(cRPair([1],[v7[1]]))` ([1.4] instead of [1.0], so here I gave up.
I'd prefer to take the if-then-else variant, at least this one was running as expected.
- as a final thought: If at some point you decide to no longer support Zygote (or keep it separate), I guess it makes more sense to put the PairWithCacheRetrieve together with the ScaleSum into one layer (and with it avoid the intermediate step which creates a vector of vectors from a vector). I can't imagine this to work without extra memory allocation.

Having all that noted down, I am fairly happy to work with my local variant of these layers for now and to let you focus more on the finalization of differentiable event indicators (since that's the clear blocking point for us now, and not the layer cosmetics).
Cheers.
