### ISSUE TITLE
How to add DistributedHyperOpt.jl is not obvius

### ISSUE THREAD

**Issue by juguma** [ThummeTo/FMIFlux.jl#115]
The example script [juliacon_2023_distributedhyperopt.jl](https://github.com/ThummeTo/FMIFlux.jl/blob/main/examples/src/juliacon_2023_distributedhyperopt.jl) uses[ DistributedHyperOpt.jl](https://github.com/ThummeTo/DistributedHyperOpt.jl), which is not included in the Project.toml, and can neither be added via Pkg.add(DistributedHyperOpt.jl).  
The script or Project.toml or DistributedHyperOpt.jl should be modified such that adding and using this package is possible. Otherwise the user has a hard time finding this package and can only guess it is one of the ThummeTo-repos.

**Comment by ThummeTo** [comment]
Correct, it's not registrated for now.
