### ISSUE TITLE
Example-FMUs work in Linux?

### ISSUE THREAD

**Issue by mroehrl** [ThummeTo/FMIFlux.jl#24]
Thanks you for the nice repository! I tried to run the examples and get the following error:
```
realFMU = fmiLoad(realFMUPath)
[ Info: fmi2Unzip(...): Successfully unzipped 28 files at `/tmp/fmijl_Gr71rS/SpringFrictionPendulum1D`.
ERROR: LoadError: AssertionError: Target platform is Linux, but can't find valid FMU binary at `` for path `/tmp/fmijl_Gr71rS/SpringFrictionPendulum1D`.
```
I think this is because I work in linux and the FMU only works in windows. Is that possible? Are there also Linux-FMUs for the examples?

**Comment by mroehrl** [comment]
Problem solved! I compiled the required binaries for linux with [fmpy](https://github.com/CATIA-Systems/FMPy). Now the example runs smootly 👍

**Comment by ThummeTo** [comment]
Good to hear that!
As you said, the FMUs in the Repo are currentyl only compiled for windows.
