### ISSUE TITLE
Dense constructor throws error

### ISSUE THREAD

**Issue by TheGadgeteer** [ThummeTo/FMIFlux.jl#77]
When trying to initialize a Dense layer by passing the weight matrix as an argument, an error is thrown.
Examples: 
`FMIFlux.Dense(ones(2,2))`
`FMIFlux.Dense(ones(2,2), zeros(2))`
The error message is  " got unsupported keyword argument "init" " and is caused in flux_overload.jl .

The issue is that Flux.Dense doesnt take an argument `init` when passing the weight matrix (and bias), however FMIFlux.Dense passes an `init` argument anyway. These are the valid calls:
`Flux.Dense(ones(2,2))`
`Flux.Dense(ones(2,2), zeros(2))`

**Comment by ThummeTo** [comment]
closed with #79
