### ISSUE TITLE
Using `ChainRulesCore` for adjoint definition

### ISSUE THREAD

**Issue by rejuvyesh** [ThummeTo/FMIFlux.jl#9]
Using `rrule` from `ChainRules` would be a lot more general and allow using other AD frameworks than Zygote.

**Comment by rejuvyesh** [comment]
https://juliadiff.org/ChainRulesCore.jl/stable/converting_zygoterules.html would be useful.

**Comment by ThummeTo** [comment]
Thanks! Absolutely, it's on the ToDo-list and even mentioned as future work in the realted publication. We are currently preparing a larger patch, releasing in about 2-3 weeks together with an update for FMI.jl. We will try to consider this point as well.

**Comment by ThummeTo** [comment]
Probably, the right way today would be to use [AbstractDifferentiation.jl](https://arxiv.org/pdf/2109.12449.pdf)?

**Comment by rejuvyesh** [comment]
@ThummeTo I don't think so. AbstractDifferentiation.jl is more about say switching between Zygote or ForwardDiff or Diffractor that chain together individual rules for function gradients. But here what we are doing is in a sense defining a gradient rule for our function and that should still be ChainRules[Core], I think.

**Comment by ThummeTo** [comment]
Added ChainRulesCore and ForwardDiff-Fallback in #15
